test:opensuse:
  image: drfaustroll/esl:opensuse-tumbleweed
  script:
    - source /etc/profile.d/lmod.sh
    - module load gnu/7  openmpi/3.0.0 scalapack/2.0.2
    - export LIBRARY_PATH=$LD_LIBRARY_PATH:$LIBRARY_PATH
    - ./jhbuild.py -f rcfiles/opensuse-gcc-openmpi.rc build esl-bundle

test:debian-debian:
  image: drfaustroll/esl:debian-latest
  script:
    - ./jhbuild.py -f rcfiles/debian-gcc-openmpi.rc build esl-bundle
