stages:
  - test 

opensuse-mpi:
  image: drfaustroll/esl:opensuse-tumbleweed
  stage: test
  script:
    - source /etc/profile.d/lmod.sh
    - module load gnu/8  openmpi/3.1.1 scalapack/2.0.2 fftw/3.3.6
    - export LIBRARY_PATH=$LD_LIBRARY_PATH:$LIBRARY_PATH
    - ./jhbuild.py -f rcfiles/opensuse-gcc-openmpi.rc build esl-bundle-mpi

opensuse-serial:
  image: drfaustroll/esl:opensuse-tumbleweed
  stage: test
  script:
    - source /etc/profile.d/lmod.sh
    - module load gnu/8 fftw/3.3.6
    - export LIBRARY_PATH=$LD_LIBRARY_PATH:$LIBRARY_PATH
    - ./jhbuild.py -f rcfiles/opensuse-gcc-serial.rc build esl-bundle

debian-mpi:
  image: drfaustroll/esl:debian-latest
  stage: test
  script:
    - ./jhbuild.py -f rcfiles/debian-gcc-openmpi.rc build esl-bundle-mpi

debian-serial:
  image: drfaustroll/esl:debian-latest
  stage: test
  script:
    - ./jhbuild.py -f rcfiles/debian-gcc-serial.rc build esl-bundle
